const nodes = [
    {
        id: '1',
        name: 'Ram',
        insulin: 1,
        email: 'Ram@gmail.com',
        strips: 1,
        nodes: 3,
    },
    {
        id: '2',
        name: 'Rahul',
        insulin: 5,
        email: 'Rahul@gmail.com',
        strips: 1,
        nodes: 3,
    },
    {
        id: '3',
        name: 'Abhishek',
        insulin: 3,
        email: 'Abhishek@gmail.com',
        strips: 2,
        nodes: 3,
    },
    {
        id: '4',
        name: 'Gautam',
        insulin: 2,
        email: 'Gautam@gmail.com',
        strips: 1,
        nodes: 3,
    },
    {
        id: '5',
        name: 'Sahil',
        insulin: 1,
        email: 'Sahil@gmail.com',
        strips: 1,
        nodes: 3,
    },
    {
        id: '6',
        name: 'Shaan',
        insulin: 6,
        email: 'Shaan@gmail.com',
        strips: 1,
        nodes: 3,
    },
    {
        id: '7',
        name: 'Amit',
        insulin: 2,
        email: 'Amit@gmail.com',
        strips: 2,
        nodes: 3,
    },
    {
        id: '8',
        name: 'Gagan',
        insulin: 2,
        email: 'Gagan@gmail.com',
        strips: 2,
        nodes: 3,
    },
    {
        id: '9',
        name: 'Rohan',
        insulin: 3,
        email: 'Rohan@gmail.com',
        strips: 2,
        nodes: 3,
    },
];

export default nodes;